### ISSUE TITLE
Front Page Customer

### ISSUE THREAD

**Issue by Jason-the-sloth** [rosemaimela/flow-gear-project#7]
![All store](https://github.com/rosemaimela/flow-gear-project/assets/169756158/94d91d24-9471-40e3-864b-6ede88f8957b)
Please create dummy data for testing front end in another method that will mimic flowgear response.
This page will need two calls to the back end
Get all tags and get list of stock. The list of stock will also incorporate a filter for tag and name

You have a choice to either have a carousel that auto populates the top bar on tags (multiple choice) or have a drop down that offers more tags that are multi select. Alternatively, combination of the two, speak to Neo about this.

What we need to do is just pass on the ids of the stock to checkout

**Comment by neotshoana** [comment]
I've added this to the pr that I made for issue  #2

**Comment by neotshoana** [comment]
The only thing missing is the radio boxes/selection filter. Not sure wihat the limitation of those impose
